### ISSUE TITLE
Add a recursive 'breakOn' function

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Pipes-ByteString-Library#27]
That would be a nice addition.

I actually need to break a bytestring into chunk separated by `\n\n` (I have not chosen that encoding).

This is similar to `partition` in python.

**Comment by mrijkeboer** [comment]
Any update on this?

**Comment by Gabriel439** [comment]
@mrijkeboer: I have a pull request up that implements `breakOn`: https://github.com/Gabriel439/Haskell-Pipes-ByteString-Library/pull/50

Take a look at that and let me know if that looks good to you.  If nobody complains then I'll merge after a week

**Comment by mrijkeboer** [comment]
@Gabriel439: I don't consider myself qualified to comment on your code. However, would it be possible to make the function without the `Lens'`? I would like to use it without using lenses. Or am I missing something?

**Comment by Gabriel439** [comment]
If the `lens` dependency bothers you, you can use the `microlens` library, which is a very lightweight dependency since it only depends on `transformers`.  That provides a `view` function you can use to get the corresponding function.

However, I would prefer to keep the lens, because then you can do things like this:

```haskell
over (breakOn "\r\n" . individually) (<* yield "!")
```

... which adds an exclamation mark to the end of each line of a file with Windows line-endings

**Comment by mrijkeboer** [comment]
That sounds fair enough. Thanks for the explanation.

**Comment by Gabriel439** [comment]
You're welcome!

**Comment by dimbleby** [comment]
If I `breakOn` and then join it all back together, shouldn't I end up where I started?

```haskell
> let producer = Pipes.ByteString.fromLazy $ Data.ByteString.Lazy.Char8.pack "hello, hello, hello"
> let needle = Data.ByteString.Char8.pack "ll"
> let lens = breakOn needle
> let output = Pipes.Group.concats $ producer ^. lens
> Pipes.ByteString.toLazyM output
"heo, heo, heo"
```

Did I misunderstand something, or is this broken?

**Comment by Gabriel439** [comment]
`breakOn` removes the needle from the groups that it splits up.  If you want to end up back where you started, you would use `Pipes.Group.intercalates (yield needle)`

In fact, the `breakOn` lens can easily be generalized to an `Iso` which would let you retrieve the opposite transformation using `Control.Lens.review`:

```haskell
review (breakOn needle)  -- This would be the same as `intercalates (yield needle)`
```

I'll make a separate change to to do that

**Comment by dimbleby** [comment]
Really?  `breakOn` doesn't remove the needle in `stringsearch` or `text` - do you really intend that this one does?

Actually, I'm not sure that `breakOn` is a great name for this implementation, since it's not really quite analagous to those other functions.  At any rate, it seems to have confused me...

(Also I noticed that the implementation - which admittedly I don't really understand! - already does some `PG,intercalates (yield needle)` stuff, so I'd guessed that you were intending that `breakOn` included the needle in the way that I'd expected.)

**Comment by dimbleby** [comment]
If I understand well then, yes, `splitOn` is a name that would fit much better with other functions of that same name.

The rest is currently over my head - and it's bedtime! - but I do appreciate you writing it out and will chew on this further as and when I come to try and use this stuff for real...
